_schema: _schema
source: out/
paths:
  uploads: public/uploads
  static: ''
collections_config:
  cloudcannon:
    path: cloudcannon
    glob:
      -
    name: Cloudcannon
    icon: '360'
    description: ''
    preview:
      text: zvzcv
      subtext: zcvzcxv
      icon:
      icon_color: '#c63c3c'
      image:
      metadata:
      gallery:
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
collection_groups:
  - heading:
    collections:
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
